# Development profile
spring:
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/gjp_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

security:
  jwt:
    secret-key: Y1uwYLhPmjd42iuEpwoXTMxg1PUKaOftH3zfWZ0vHyzTpJrh4JDbBZFvgjj5ZH/D

# Logging configuration
logging:
  level:
    org.ganjp.api: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
